kafka:
  image: spotify/kafka
  ports:
    - "2181:2181"
    - "9092:9092"
  environment:
    ADVERTISED_HOST: localhost
    ADVERTISED_PORT: 9092
    CONSUMER_THREADS: 1
    TOPICS: user
    ZK_CONNECT: kafka7zookeeper:2181/root/path
    GROUP_ID: automec-finder
    NUM_PARTITIONS: 100

mongo:
  image: mongo
  restart: unless-stopped
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
  ports:
    - "27017:27017"