server:
  port: 8081

spring:
  application:
    name: automec-finder-basic

  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/automec-finder?authSource=admin
  kafka:
      bootstrap-servers: localhost:9092
      advertised:
        host:
          name: localhost
        port: 9092
      listener:
          concurrency: 1
      consumer:
          topic: "user"
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer